// Root
export const AUTHENTICATION = 'AUTHENTICATION';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SHOW_GLOBAL_LOADER = 'SHOW_GLOBAL_LOADER';
export const HIDE_GLOBAL_LOADER = 'HIDE_GLOBAL_LOADER';
export const SHOW_BOTTOM_SHEET = 'SHOW_BOTTOM_SHEET';
export const HIDE_BOTTOM_SHEET = 'HIDE_BOTTOM_SHEET';
